### ISSUE TITLE
Big DLC files do not work

### ISSUE THREAD

**Issue by mbosner** [pyload/pyload#1076]
When i try to import rather big dlc files with some hundreds of parts i see this error in the console:

```
Traceback (most recent call last):
  File "/pyload/stable/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/pyload/stable/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/pyload/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/pyload/stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "/pyload/stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/pyload/stable/module/lib/bottle.py", line 928, in forms
    for name, item in self.POST.iterallitems():
  File "/pyload/stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/pyload/stable/module/lib/bottle.py", line 1018, in POST
    fb = self.body
  File "/pyload/stable/module/lib/bottle.py", line 999, in body
    self._body.seek(0)
  File "/pyload/stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
AssertionError: recv(4096) returned 16384 bytes
An error occured while processing the request.
```

**Comment by vuolter** [comment]
Un-fixable in stable branch. :(

**Comment by vuolter** [comment]
@mbosner I just tried with a dlc of 100+ links and cnl works fine. Could you post a sample url, please?

**Comment by mbosner** [comment]
The problem starts around 400-500 links in one DLC. Posting a sample url is - difficult.

**Comment by vuolter** [comment]
I need it to reproduce this issue.

**Comment by mbosner** [comment]
Ok. http://test.tvsr.de/test.dlc
Please comment as soon as you downloaded it.

**Comment by vuolter** [comment]
Done. :)

**Comment by vuolter** [comment]
And... all works on my end. :/

**Comment by vuolter** [comment]
https://github.com/pyload/pyload/commit/7a0c370482142b113ab70fa1bb1446223a707c62

**Comment by mbosner** [comment]
You did not fix it in stable branch, did you?

With 181d163cd02e710f7d36fb9ce6095d2332e579c8 i get this:

An error occured while processing the request.
Traceback (most recent call last):
  File "stable/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "stable/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "stable/module/lib/bottle.py", line 928, in forms
    for name, item in self.POST.iterallitems():
  File "stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "stable/module/lib/bottle.py", line 1018, in POST
    fb = self.body
  File "stable/module/lib/bottle.py", line 999, in body
    self._body.seek(0)
  File "stable/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
AssertionError: recv(4096) returned 16384 bytes

**Comment by vuolter** [comment]
Try reinstalling bottle.py (`pip install bottle`).

**Comment by mbosner** [comment]
reinstalling?! it is not installed at all ... Currently i am using system packages for the whole setup:
http://pyload.org/de:pyload_stepbystep_linux and that says:

```
apt-get install python-crypto python-pycurl python-imaging python-beaker python-qt4 tesseract-ocr tesseract-ocr-eng gocr unrar
```


Should i remove all system libs and use pip or even go for pyenv + python + pip?

**Comment by mbosner** [comment]
Just installed pip and upgraded to latest bottle (0.12.8)

I still get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/data/pyload-versions/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/data/pyload-versions/stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1084, in forms
    for name, item in self.POST.allitems():
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1226, in POST
    args = dict(fp=self.body, environ=safe_env, keep_blank_values=True)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1197, in body
    self._body.seek(0)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1166, in _body
    for part in body_iter(read_func, self.MEMFILE_MAX):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1129, in _iter_body
    part = read(min(maxread, bufsize))
  File "/data/pyload-versions/stable/module/lib/wsgiserver/__init__.py", line 199, in read
    data = self.rfile.read(size)
  File "/data/pyload-versions/stable/module/lib/wsgiserver/__init__.py", line 806, in read
    assert n <= left, "recv(%d) returned %d bytes" % (left, n)
AssertionError: recv(4096) returned 16384 bytes
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/data/pyload-versions/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/data/pyload-versions/stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1084, in forms
    for name, item in self.POST.allitems():
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1226, in POST
    args = dict(fp=self.body, environ=safe_env, keep_blank_values=True)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1197, in body
    self._body.seek(0)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1166, in _body
    for part in body_iter(read_func, self.MEMFILE_MAX):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1129, in _iter_body
    part = read(min(maxread, bufsize))
  File "/data/pyload-versions/stable/module/lib/wsgiserver/__init__.py", line 199, in read
    data = self.rfile.read(size)
  File "/data/pyload-versions/stable/module/lib/wsgiserver/__init__.py", line 806, in read
    assert n <= left, "recv(%d) returned %d bytes" % (left, n)
AssertionError: recv(4096) returned 16384 bytes
```

**Comment by mbosner** [comment]
Btw. is it possible to donate somehow? Could not finden a link ...

**Comment by vuolter** [comment]
Nope, currently.

**Comment by vuolter** [comment]
Please, enable debug mode, then retry to download a dlc. Finally look in your pyload config for a file starting with 'debug_' and post it content here (better if on pastebin or such so).

**Comment by mbosner** [comment]
There are no debug lines, no debugfile in the config and no debug file - debugging is on.

From the normal logfile:

```
29.01.2015 16:49:38 INFO      Starting pyLoad 0.4.9
29.01.2015 16:49:38 INFO      Using home directory: /xxx/pyload
29.01.2015 16:49:38 DEBUG     Remote activated: False
29.01.2015 16:49:38 DEBUG     created index of plugins
29.01.2015 16:49:38 INFO      ExtractArchive: No SevenZip installed
29.01.2015 16:49:38 INFO      ExtractArchive: Activated UnRar UnZip
29.01.2015 16:49:38 INFO      Activated plugins: Captcha9Kw, ClickAndLoad, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, XFileSharingPro
29.01.2015 16:49:38 INFO      Deactivate plugins: AlldebridCom, AndroidPhoneNotify, BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneToastNotify, XMPPInterface, ZeveraCom
29.01.2015 16:49:38 INFO      Downloadtime: True
29.01.2015 16:49:39 INFO      Starting threaded SSL webserver: 0.0.0.0:1800
29.01.2015 16:49:39 INFO      Free space: 26.45 TiB
29.01.2015 16:49:39 INFO      Activating Accounts...
29.01.2015 16:49:39 DEBUG     UploadedTo: Get Account Info for 00000
29.01.2015 16:49:39 DEBUG     UploadedTo: Account Info: {'premium': True, 'validuntil': 1421180529.347611, 'trafficleft': 1010953093.12}
29.01.2015 16:49:39 DEBUG     ShareonlineBiz: Get Account Info for 0010101010101
29.01.2015 16:49:39 DEBUG     ShareonlineBiz: {'a': 'not_available', 'traffic_7d': '0;0.000', 'group': 'Sammler', 'traffic_1d': '0;0.000', 'money': '5.00', 'register_date': '1413111865', 'points': '5000', 'user': '0010101010101', 'expire_date': '-1', 'email': 'yo@bo.com'}
29.01.2015 16:49:39 DEBUG     ShareonlineBiz: Account Info: {'validuntil': None, 'maxtraffic': 9999, 'premium': False, 'trafficleft': -1}
29.01.2015 16:49:39 INFO      Activating Plugins...
29.01.2015 16:49:39 INFO      XFileSharingPro: Handling any hoster I can!
29.01.2015 16:49:39 DEBUG     XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
29.01.2015 16:49:39 INFO      XFileSharingPro: Handling any crypter I can!
29.01.2015 16:49:39 DEBUG     XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
29.01.2015 16:49:39 INFO      pyLoad is up and running
29.01.2015 16:50:05 INFO      shutting down...
29.01.2015 16:50:05 DEBUG     Deleting old pidfile pyload.pid
29.01.2015 16:50:05 INFO      killed pyLoad from Terminal
```

**Comment by vuolter** [comment]
And now where is the error ant its traceback? O.o

**Comment by mbosner** [comment]
Its only in the console. It is not logged in the logfile...

**Comment by mbosner** [comment]
Full console output - from start over uploading a big file to shutdown ...

```
29.01.2015 19:08:43 INFO      Starting pyLoad 0.4.9
29.01.2015 19:08:43 INFO      Using home directory: /bin/pyloads/config
29.01.2015 19:08:43 DEBUG     Remote activated: False
29.01.2015 19:08:43 DEBUG     created index of plugins
29.01.2015 19:08:43 INFO      ExtractArchive: No SevenZip installed
29.01.2015 19:08:43 INFO      ExtractArchive: Activated UnRar UnZip
29.01.2015 19:08:43 INFO      Activated plugins: Captcha9Kw, ClickAndLoad, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, XFileSharingPro
29.01.2015 19:08:43 INFO      Deactivate plugins: AlldebridCom, AndroidPhoneNotify, BypassCaptcha, CaptchaBrotherhood, Checksum, DeathByCaptcha, DebridItaliaCom, DeleteFinished, DownloadScheduler, EasybytezCom, ExpertDecoders, FastixRu, FreeWayMe, HotFolder, IRCInterface, ImageTyperz, JustPremium, LinkdecrypterCom, LinksnappyCom, MegaDebridEu, MultiHome, MultihostersCom, MultishareCz, MyfastfileCom, NoPremiumPl, OverLoadMe, PremiumTo, PremiumizeMe, PutdriveCom, RPNetBiz, RapideoPl, RealdebridCom, RehostTo, RestartFailed, RestartSlow, SimplyPremiumCom, SimplydebridCom, SkipRev, SmoozedCom, UnrestrictLi, WindowsPhoneToastNotify, XMPPInterface, ZeveraCom
29.01.2015 19:08:43 INFO      Downloadtime: True
29.01.2015 19:08:44 INFO      Starting threaded SSL webserver: 0.0.0.0:18000
29.01.2015 19:08:44 INFO      Free space: 26.41 TiB
29.01.2015 19:08:44 INFO      Activating Accounts...
29.01.2015 19:08:44 DEBUG     UploadedTo: Get Account Info for 111111
29.01.2015 19:08:44 DEBUG     UploadedTo: Account Info: {'premium': True, 'validuntil': 1428181724.303128, 'trafficleft': 1010953093.12}
29.01.2015 19:08:44 DEBUG     ShareonlineBiz: Get Account Info for 22222222
29.01.2015 19:08:44 DEBUG     ShareonlineBiz: {'a': 'not_available', 'traffic_7d': '0;0.000', 'group': 'Sammler', 'traffic_1d': '0;0.000', 'money': '5.00', 'register_date': '1413123865', 'points': '5000', 'user': '22222222', 'expire_date': '-1', 'email': 'info@nonono.de'}
29.01.2015 19:08:44 DEBUG     ShareonlineBiz: Account Info: {'validuntil': None, 'maxtraffic': 104857600, 'premium': False, 'trafficleft': -1}
29.01.2015 19:08:44 INFO      Activating Plugins...
29.01.2015 19:08:44 INFO      XFileSharingPro: Handling any hoster I can!
29.01.2015 19:08:44 DEBUG     XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
29.01.2015 19:08:44 INFO      XFileSharingPro: Handling any crypter I can!
29.01.2015 19:08:44 DEBUG     XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?P<DOMAIN>[\w.^_]+(?:\.[a-zA-Z]{2,})(?:\:\d+)?)/(?:user|folder)s?/\w+
29.01.2015 19:08:44 INFO      pyLoad is up and running
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/bin/pyloads/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/bin/pyloads/stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1084, in forms
    for name, item in self.POST.allitems():
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1226, in POST
    args = dict(fp=self.body, environ=safe_env, keep_blank_values=True)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1197, in body
    self._body.seek(0)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1166, in _body
    for part in body_iter(read_func, self.MEMFILE_MAX):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1129, in _iter_body
    part = read(min(maxread, bufsize))
  File "/bin/pyloads/stable/module/lib/wsgiserver/__init__.py", line 199, in read
    data = self.rfile.read(size)
  File "/bin/pyloads/stable/module/lib/wsgiserver/__init__.py", line 806, in read
    assert n <= left, "recv(%d) returned %d bytes" % (left, n)
AssertionError: recv(4096) returned 16384 bytes
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/bin/pyloads/stable/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/bin/pyloads/stable/module/web/json_app.py", line 157, in add_package
    name = request.forms.get("add_name", "New Package").strip()
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1084, in forms
    for name, item in self.POST.allitems():
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1226, in POST
    args = dict(fp=self.body, environ=safe_env, keep_blank_values=True)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1197, in body
    self._body.seek(0)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1166, in _body
    for part in body_iter(read_func, self.MEMFILE_MAX):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1129, in _iter_body
    part = read(min(maxread, bufsize))
  File "/bin/pyloads/stable/module/lib/wsgiserver/__init__.py", line 199, in read
    data = self.rfile.read(size)
  File "/bin/pyloads/stable/module/lib/wsgiserver/__init__.py", line 806, in read
    assert n <= left, "recv(%d) returned %d bytes" % (left, n)
AssertionError: recv(4096) returned 16384 bytes
29.01.2015 19:09:02 INFO      shutting down...
29.01.2015 19:09:02 DEBUG     Deleting old pidfile pyload.pid
29.01.2015 19:09:02 INFO      killed pyLoad from Terminal
```

**Comment by vuolter** [comment]
I have no solution, continue to work fine for me. Try reinstalling pyload at all. :(

**Comment by mbosner** [comment]
Could you tell me your setup, please? E.g. which python version, platform etc. ?

**Comment by vuolter** [comment]
I tried on windows 7 sp1 x64, latest xubuntu x64 and latest tomato by shibby firmware and works fine on all of them, using the offical packages (and the entware package for tomato).
