### ISSUE TITLE
external scripts did not work

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1233]
Since version 0.31 or 0.32, the external scripts did not work.
5241	09.03.2015 05:47:00	DEBUG	All downloads processed
5240	09.03.2015 05:47:00	WARNING	Error calling event handler allDownloadsProcessed: >, (), 'all_downloads_processed'

**Comment by jbman11** [comment]
I am seeing the same thing

WARNING	Error calling event handler allDownloadsProcessed: >, (), 'all_downloads_processed'
WARNING	Error calling event handler allDownloadsFinished: >, (), 'all_downloads_finished'

**Comment by Mister-XY** [comment]
Ah anything must also be wrong with the new version, i also get an error with v0.35.
He did not load correctly the external script.
3503	18.03.2015 18:31:45	DEBUG	ExternalScripts: Executing: /home/thomas/.pyload/scripts/package_extracted/package_extracted.sh | Args: 330 xxx /mnt/md0/Download/xxx
3502	18.03.2015 18:31:45	WARNING	Error calling event handler archive_extracted: >, (PyFile 824: xxx.rar@UploadedTo, u'/mnt/md0/Download/xxx/', u'/mnt/md0/Download/xxx/xxx.rar', [u'/mnt/md0/Download/xxx/xxx', u'/mnt/md0/Download/xxx/xxx/xxx.nfo', u'/mnt/md0/Download/xxx/xxx/xxx.mkv']), archive_extracted() takes exactly 3 arguments (5 given)
3501	18.03.2015 18:31:45	DEBUG	ExtractArchive: Extracted files: [u'/mnt/md0/Download/xxx/xxx', u'/mnt/md0/Download/xxx/xxx/xxx.nfo', u'/mnt/md0/Download/xxx/xxx/xxx.mkv']

**Comment by Ghoststage** [comment]
@vuolter 

Testest du auch dein gefummele?

**Comment by johtso** [comment]
Is it possible to get a bugfix release with the unicode error fixes? Seems a pretty critical issue, pyload's currently unusable for me until this is released.

**Comment by Mister-XY** [comment]
withe the new script, now it's work but if you use $1, $2 etc. you must change it.

**Comment by johtso** [comment]
@Mister-XY how are you running the new code? are you manually checking it out from github?

**Comment by Mister-XY** [comment]
Did you mean the new externalscript.py or did you mean my personal script?
If you mean my personal script, i have look for the ID.
I#m using a script after package_extracted, so i have put into the script
echo -e "$1 Name" >>/tmp/test.txt
echo -e "$2 Verzeichnis" >>/tmp/test.txt
echo -e "$3 Password" >>/tmp/test.txt
I have write after $1,$2,$3 the old ID's and can now compare between old and new ID.
In my case the Old ID $2 changed to ID $3 after the update from extrenalscript.

**Comment by vuolter** [comment]
@johtso Unicode error was fixed.
@Mister-XY @Ghoststage See: http://forum.pyload.org/viewtopic.php?f=12&t=4158#p17579

**Comment by johtso** [comment]
@vuolter how can I run the new code with the fix? Should the update be automatically installed? I'm seeing no plugin updates.

**Comment by Mister-XY** [comment]
Yes, the update will installed via update manager.

**Comment by johtso** [comment]
@vuolter I'm still seeing the unicode errors. Do I need to wait until 0.4.10 ships? Or is there anything else I can check?

**Comment by Mister-XY** [comment]
wich version from external script do you have?

**Comment by johtso** [comment]
@Mister-XY I have version `0.23`

**Comment by Mister-XY** [comment]
Ok version 0.37 is aviable.

**Comment by vuolter** [comment]
@johtso You mean the unicode error due to filename encoding when downloading?

**Comment by johtso** [comment]
@vuolter yep that's the one. Turns out it was because my locale was ASCII. Ended up being a nightmare trying to get a UTF-8 locale to stick inside a freenas jail. I opened an issue regarding it here: https://github.com/pyload/pyload/issues/1277

**Comment by Mister-XY** [comment]
Is it possible that password's did not give to an external script? With the old external script, i have a password and these password was given to an external script, but with the new, i can't the theses function.

**Comment by vuolter** [comment]
@Mister-XY https://github.com/pyload/pyload/commit/031cc3a5f5b842698c0323fbec7d7a33f3ca99f8
