### ISSUE TITLE
[Uploaded.To] fall back to free-account

### ISSUE THREAD

**Issue by Web-Eye** [pyload/pyload#1622]
every uploaded.to download falls back to free-account, although valid prem account is available.
Additional bug: no new account subsription is possible, I think it's the same error.

Maybe this is a multipost, see #1590, apologize...

Here is is my full debug log:
```
112	30.07.2015 18:12:11	INFO	ACCOUNT UploadedTo: Parsing account info for user `{user}`...
113	30.07.2015 18:12:11	DEBUG	ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
114	30.07.2015 18:12:11	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
115	30.07.2015 18:12:11	INFO	Download starts: http://ul.to/xxx
116	30.07.2015 18:12:11	DEBUG	HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
117	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: PROCESS URL http://ul.to/xxx
118	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: Updating file info...
119	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: File info: {'status': 2, 'url': u'http://uploaded.net/file/xxx', 'size': 157286400.0, 'name': 'xxx.rar', 'pattern': {'ID': u'xxx'}}
120	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: Previous file info: {}
121	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: File name: xxx.rar
122	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: File size: 157286400 bytes
123	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: File status: online
124	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: Looking for direct download link...
125	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: Redirect #0 to: http://uploaded.net/file/xxx
126	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://uploaded.net/file/xxx | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
127	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: Direct download link not found
128	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://uploaded.net/file/xxx | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=False
129	30.07.2015 18:12:11	INFO	HOSTER UploadedTo[3044]: Processing as free download...
130	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | just_header=True | post={} | ref=True
131	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://uploaded.net/js/download.js | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
132	30.07.2015 18:12:11	DEBUG	CAPTCHA UploadedTo[3044]: ReCaptcha | Key: 6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3
133	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://www.google.com/recaptcha/api/challenge | cookies=True | get={'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | just_header=False | post={} | ref=True
134	30.07.2015 18:12:11	DEBUG	CAPTCHA UploadedTo[3044]: ReCaptcha | Challenge: 03AHJ_VuvlluwSoval98CVsBDLZavXQO6qpRdn4h5hRxaMeVxLs2OfT-hDdBIZYzAqlEr9Rk9eL_5-XJVhszUL2pDnCWTR7l_9VUfdHlHsw7bTT4CvgcHzebQFAQ4qaPMoJErcD29FamvYBYzpn6cSQZKpm3gsnfKCUynmsK8T6YptvA3C1P5aej4CjUj63DopTp1uRx2tgvehBYT2AZ1300xkQIR5PyuceA
135	30.07.2015 18:12:11	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://www.google.com/recaptcha/api/js/recaptcha.js | cookies=True | get={} | req=None | decode=True | just_header=False | post={} | ref=True
136	30.07.2015 18:12:12	DEBUG	HOSTER UploadedTo[3044]: LOAD URL http://www.google.com/recaptcha/api/reload | cookies=True | get={'reason': 'i', 'c': u'03AHJ_VuvlluwSoval98CVsBDLZavXQO6qpRdn4h5hRxaMeVxLs2OfT-hDdBIZYzAqlEr9Rk9eL_5-XJVhszUL2pDnCWTR7l_9VUfdHlHsw7bTT4CvgcHzebQFAQ4qaPMoJErcD29FamvYBYzpn6cSQZKpm3gsnfKCUynmsK8T6YptvA3C1P5aej4CjUj63DopTp1uRx2tgvehBYT2AZ1300xkQIR5PyuceA', 'type': 'image', 'k': u'6Lcqz78SAAAAAPgsTYF3UlGf2QFQCNuPMenuyHF3'} | req=None | decode=True | just_header=False | post={} | ref=True
137	30.07.2015 18:12:12	DEBUG	CAPTCHA UploadedTo[3044]: ReCaptcha | Second challenge: 03AHJ_VuuCwjhYzpboP3B4QIZ-DASNQMdhnOLiDYCYjHQMupbrzu0eZcdama5qcvKc0dX-M1CGyQSPQwsEVi4hLLgComEVKiKWCx396j-H1rHq8Zts628i5EnDmmA9pYVnvd2Xy3GBGcdZrGgDdWwgFm68Idc-9wb4NFhT8c01B0zeIje0sFMqS__zSWGptMp8uy6tSo1BELH44bM6SLN63VonnO23RqVHxA
138	30.07.2015 18:12:12	DEBUG	CAPTCHA UploadedTo[3044]: ReCaptcha | LOAD URL http://www.google.com/recaptcha/api/image | cookies=True | get={'c': u'03AHJ_VuuCwjhYzpboP3B4QIZ-DASNQMdhnOLiDYCYjHQMupbrzu0eZcdama5qcvKc0dX-M1CGyQSPQwsEVi4hLLgComEVKiKWCx396j-H1rHq8Zts628i5EnDmmA9pYVnvd2Xy3GBGcdZrGgDdWwgFm68Idc-9wb4NFhT8c01B0zeIje0sFMqS__zSWGptMp8uy6tSo1BELH44bM6SLN63VonnO23RqVHxA'} | req=None | decode=False | just_header=False | post={} | ref=False
139	30.07.2015 18:12:13	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
140	30.07.2015 18:12:15	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
141	30.07.2015 18:12:17	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
142	30.07.2015 18:12:19	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
143	30.07.2015 18:12:21	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
144	30.07.2015 18:12:23	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
145	30.07.2015 18:12:25	DEBUG	ACCOUNT UploadedTo: Account info for user `{user}`: {'login': {'timestamp': 1438272440.825602, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1440857531.203805, 'valid': True, 'trafficleft': 552977039360.0, 'timestamp': 1438272731.020294, 'maxtraffic': None, 'premium': True, 'login': '{user}', 'password': '**********', 'type': 'UploadedTo', 'options': {'limitdl': '0'}}}
146	30.07.2015 18:12:26	INFO	Download aborted: http://uploaded.net/file/xxx
147	30.07.2015 18:12:26	DEBUG	All downloads processed 
```

I hope this will help.

Regards,
WebEye

**Comment by boerngen-schmidt** [comment]
I had the same problem, but it seems to be fixed in the latest version (I did a git clone). only thing that happens now is that during the download filenames are hashes, but after the download is done they have their real name

**Comment by scrimpy** [comment]
Yes this is fixed.

**Comment by Web-Eye** [comment]
don't work for me! I did a git clone fron 'https://github.com/pyload/pyload.git' and turned off updatemanager! Now the Linkdecrypter seems not to work, plus the multi-mentioned "AttributeError: 'NoneType' object has no attribute 'close'" bug...

I try old userplugin backups, playing with userrights, noting works, so I have to wait for the fix....

**Comment by scrimpy** [comment]
i wish i had such backup too.

**Comment by Web-Eye** [comment]
@scrimpy: look at http://forum.pyload.org/viewtopic.php?f=10&t=1552&p=19087#p19087
There is backup of my userplugins

**Comment by uk3k** [comment]
Problem still persists!
@Web-Eye, even using your backup doesn't work for me anymore.

**Comment by vuolter** [comment]
Now should work.

**Comment by Web-Eye** [comment]
just updated via update manager and it seems to work! Only ClickAndLoad throwed an error, but I don't use it.

**Comment by vuolter** [comment]
@Web-Eye Post the CNL error. ;)

**Comment by Web-Eye** [comment]
@vuolter see #2005 ;)
btw: thanks for support, I have to mention this....
