### ISSUE TITLE
Error loading info for user `1234567890` | invalid literal for float()

### ISSUE THREAD

**Issue by ace02000** [pyload/pyload#1894]
Hi,
I get following error with a premium uploaded.net account.

>30.09.2015 09:13:13 INFO      Activating Accounts...
>30.09.2015 09:13:13 INFO      ACCOUNT UploadedTo: Adding user `1234567890`...
>30.09.2015 09:13:13 INFO      ACCOUNT UploadedTo: Login user `1234567890`...
>30.09.2015 09:13:13 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/language/en | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
>30.09.2015 09:13:13 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/io/login | cookies=True | get={} | req=None | decode=True | multipart=False | post={'id': '1234567890', 'pw': 'XXXXXXXXXXXXXX'} | ref=True | just_header=False
>30.09.2015 09:13:13 INFO      ACCOUNT UploadedTo: Grabbing account info for user `1234567890`...
>30.09.2015 09:13:13 DEBUG     ACCOUNT UploadedTo: LOAD URL http://uploaded.net/me | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
>30.09.2015 09:13:13 WARNING   ACCOUNT UploadedTo: Error loading info for user `1234567890` | invalid literal for float(): 123.73gb
>30.09.2015 09:13:13 DEBUG     ACCOUNT UploadedTo: Account info for user `1234567890`: {'login': {'timestamp': 1443597193.322237, 'password': '**********', 'valid': True}, 'data': {'validuntil': None, 'maxtraffic': None, 'premium': None, 'options': {'limitdl': ['0']}, 'trafficleft': None}}
>30.09.2015 09:13:13 INFO      Activating Plugins...
>30.09.2015 09:13:13 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager.pyload.org | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
>30.09.2015 09:13:13 WARNING   ADDON AntiStandby: Unable to change system power state | [Errno 2] No such file or directory
>30.09.2015 09:13:13 INFO      HOOK XFileSharingPro: Handling any hoster I can!
>30.09.2015 09:13:13 DEBUG     HOOK XFileSharingPro: Loaded hoster pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
>30.09.2015 09:13:13 INFO      HOOK XFileSharingPro: Handling any crypter I can!
>30.09.2015 09:13:13 DEBUG     HOOK XFileSharingPro: Loaded crypter pattern: https?://(?:www\.)?(?:\w+\.)*?(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,}(?:\.[a-zA-Z]{2,}){1,2})(?:\:\d+)?)/(?:user|folder)s?/\w+
>30.09.2015 09:13:14 DEBUG     ADDON ExtractArchive: Found UnRar 4.10 | Found UnZip 2.7.3
>30.09.2015 09:13:14 INFO      pyLoad is up and running

**Comment by DomiakaSnakez** [comment]
Same Here
30.09.2015 09:26:28 WARNING   ACCOUNT UploadedTo: Error loading info for user `127*****` | invalid literal for float(): 505.00gb

**Comment by DomiakaSnakez** [comment]
Same here

**Comment by must4rd** [comment]
Same!

**Comment by ace02000** [comment]
the fix works but now I got a new error :/

> 30.09.2015 13:27:05 WARNING   Download failed: test.rar | get_data() got an unexpected keyword argument 'refresh'

**Comment by DomiakaSnakez** [comment]
After the Fix, Premium works. But i got a new error
>30.09.2015 13:35:31 WARNING   Download failed: example.rar | get_data() got an unexpected >keyword argument 'refresh'

**Comment by ace02000** [comment]
Debug Log ...
>30.09.2015 13:45:08 WARNING   Download failed: test.rar | get_data() got an unexpected keyword argument 'refresh'
>Traceback (most recent call last):
>  File "/home/pyload/pyload/module/PluginThread.py", line 187, in run
>    pyfile.plugin.preprocessing(self)
>  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 196, in preprocessing
>    return self._process(*args, **kwargs)
>  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 191, in _process
>    return self.process(self.pyfile)
>  File "/home/pyload/pyload/module/plugins/internal/SimpleHoster.py", line 273, in process
>    if self.premium and (not self.CHECK_TRAFFIC or self.check_traffic()):
>  File "/home/pyload/pyload/module/plugins/internal/Hoster.py", line 582, in check_traffic
>    traffic = self.account.get_data(refresh=True)['trafficleft']
>TypeError: get_data() got an unexpected keyword argument 'refresh'
>

**Comment by ace02000** [comment]
this fix works for me ... 18d53e0e1c1e2bf5df082886b96fae23a7fdac3a

**Comment by DomiakaSnakez** [comment]
yes, this fix works. thank you. but i have a new "problem". Download works. But now he tries to Grabb the account info twice times every second.
>30.09.2015 14:35:06 INFO      ACCOUNT UploadedTo: Grabbing account info for user `12345678`...
30.09.2015 14:35:07 INFO      ACCOUNT UploadedTo: Grabbing account info for user `12345678`...
30.09.2015 14:35:09 INFO      ACCOUNT UploadedTo: Grabbing account info for user `12345678`...
30.09.2015 14:35:09 INFO      ACCOUNT UploadedTo: Grabbing account info for user `12345678`...
...

**Comment by ace02000** [comment]
I see ... same issue :/

**Comment by kasperj** [comment]
https://github.com/pyload/pyload/pull/1895 fixed with this

**Comment by wastez** [comment]
I also had the refresh error but after the fix i´ve another one.
30.09.2015 18:51:28	WARNING	Download failed: tvs-reign-ded-dl-ithd-x264-207.part1.rar | need more than 1 value to unpack

**Comment by Frozen-byte** [comment]
I still got the error:
`01.10.2015 00:05:22 WARNING   ACCOUNT UploadedTo: Error loading info for user `user` | invalid literal for float(): 505.00gb`
last commit: #5db82ae44b

**Comment by must4rd** [comment]
still having this problem:
ACCOUNT UploadedTo: Grabbing account info for user `119...
ACCOUNT UploadedTo: Grabbing account info for user `119...
every second. i used the fixes from ace02000...any idea?

**Comment by DomiakaSnakez** [comment]
same problem
Debug:
>01.10.2015 12:44:37	DEBUG	ACCOUNT UploadedTo: Account info for user `1234567`: {'login': {'timestamp': 1443696266.086297, 'password': '**********', 'valid': True}, 'data': {'validuntil': 1489221877.141259, 'trafficleft': 521351987.2, 'maxtraffic': None, 'premium': True, 'options': {'limitdl': ['0']}}}

**Comment by ace02000** [comment]
My fix is just a workaround/quickfix, not really a bug fix ;)
Any developer have to fix this problem in a better way.
