### ISSUE TITLE
Pyload on DSM 6.0-7321

### ISSUE THREAD

**Issue by aronze06** [pyload/pyload#2397]
Hi All;

Since my morning update of my NAS in 6.0-7321, my Pyload package doesn't start and doesn't work fine.

Do you have an idea of what to do ?

Thanks to all of you !

Alexis

**Comment by feuerwasser85** [comment]
On wich way do you have installed pyload?
1. Enkidu Package of the community package
2. Bootstrap IPKG installation
3. Docker Container

The Docker method should work on any DSM cause its virtualisation.

**Comment by GammaC0de** [comment]
@aronze06 Please read #2000

**Comment by mgg1959** [comment]
Hi, i got the same problem and i got installed from http://packages.synocommunity.com/ directly from package sources on my ds412+, of course i got python  installed and pyload user enabled, pyload don't start why any message at all, http://prntscr.com/alginh this is how the pyload screen stay forever.
Thanks

**Comment by aronze06** [comment]
Hi mgg;
Read Gamma message: "@aronze06 Please read #2000" above.
I can't try it yet but I think it works.

My problem is no root ssh connection available because since DSM 6 doesn't allow it :(
I'm trying to find a solution to copy pyload folder on my NAS via SSH and via putty. But i'm not an expert and I found some difficulties.

Alexis

**Comment by mgg1959** [comment]
hi Alexis, thanks for your reply, but how i know which is the version i should get?

**Comment by aronze06** [comment]
I think you have to download this file: "pyload-src-v0.4.9.zip"

If someone know how to download folder on my NAS via putty, i'm interested by your help ;)

**Comment by mgg1959** [comment]
I hate somewhere putty or cli, i hope someone explain it in a easy way, thanks Alexis

**Comment by aronze06** [comment]
I tried with winscp but because root login is not available with DSM 6, I can't change any file :(

**Comment by GammaC0de** [comment]
@aronze06 Can you login as administrators group credentials and then issue `sudo su -`  command?

**Comment by mgg1959** [comment]
i have no clue about putty

**Comment by aronze06** [comment]
Yes I can login with my admin account. Then in "loggin" as root in using "sudo su -" command.
But with putty i don't know how to copy pyload folder (located on my computer) in my NAS (in the @appstore/pyload).

But i think we can 
In "settings>Telnet & SNMP>Advanced settings" you can set it as "low" and root login seems working fine.
I will try to test it soon. I will replace package download with "package center" and replace pyload file by those available on the link you gave me.

thanks again for your help and I'll keep you informed

PS: sorry for my english ;)

Alexis

**Comment by mgg1959** [comment]
in my DSM telnet is disabled, the  ip  is 192.168.1.7 in my nertwork, how i can enter with putty?, too many options, ssh, telnet, ,,,, thanks

**Comment by GammaC0de** [comment]
On putty check SSH, on the host , enter the ip 192.168.1.7 and then press the open button

**Comment by aronze06** [comment]
bad news... my previous test doesn't work with WinSCP ;(

**Comment by mgg1959** [comment]
done, i got root enabled sudo su - http://prntscr.com/alklgm

**Comment by aronze06** [comment]
then after root login on my NAS using "sudo su -" I tried to copy pyload file into the instal directory.
For that I enter the command below:
scp -r /volume1/Fichiers/pyload/ /volume1/@appstore/pyload/pyload/

But, files seem not well copy

**Comment by sticmou** [comment]
hi, i had to download this file: "pyload-src-v0.4.9.zip" and used the command 
scp -r /volume1/Fichiers/pyload/ /volume1/@appstore/pyload/pyload/

but ... not change ... same error ...

root@DiskStation:/volume1/@appstore/pyload/pyload# /volume1/@appstore/pyload/bin/python /volume1/@appstore/pyload/pyload/pyLoadCore.py
Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/pyLoadCore.py", line 28, in <module>
    import module.common.pylgettext as gettext
  File "/volume1/@appstore/pyload/pyload/module/common/pylgettext.py", line 4, in <module>
    from gettext import *
  File "/volume1/@appstore/pyload/lib/python2.7/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/volume1/@appstore/pyload/lib/python2.7/locale.py", line 18, in <module>
    import operator
ImportError: /volume1/@appstore/pyload/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString

**Comment by GammaC0de** [comment]
See #2399 for DSM installation.

**Comment by aronze06** [comment]
Thanks Gamma for your help but I still have a problem.

So, I tried to do some tests... inconclusive :(
Find below, step by step what I did:
- Install pyload 0.4.9.4 from "packages center" and http://packages.synocommunity.com url.
- Then I download pyload (pyload-src-v0.4.9.zip) package from "https://github.com/pyload/pyload/releases". I extract it and copy each files by ssh in "/volume1/@appstore/pyload/
- At the same time, I also modify the UpdateManager.py file to be like Gamma said me.
- I started pyload but it doesn't start. The windows opening but there is no icon as you can see with the pic 01 file 
![pic 01](https://cloud.githubusercontent.com/assets/14806027/14169440/07259e10-f728-11e5-9c8c-b8cb466373b3.jpg)

Then, I tried to stop & start pyload and relaunch it but I still have the same problem :(

I hope I'm clear and you could help me.

Thanks for your time !

Alexis

**Comment by effpi** [comment]
Here is how I worked around:
did all the steps you indicated, but did not launch package

then I connected to NAS in SSH and used: "sudo python /volume1/@appstore/pyload/pyload/pyLoadCore.py"
then could access the interface with my brower on "http://192.168.1.3:8000" (you should use your NAS ip address
this solution is not convenient as it requires to keep ssh open

in case you may need to first run "sudo python /volume1/@appstore/pyload/pyload/pyLoadCore.py -s" to set-up the app

I think part of the issue is that python is built-in DSM 6

**Comment by aronze06** [comment]
Hi effpi;

I tried to execute the command you gave me but i have an error describes in the picture bellow.

Alexis
![pic 02](https://cloud.githubusercontent.com/assets/14806027/14179096/f78db02e-f75d-11e5-9153-9add83f6207e.jpg)

**Comment by effpi** [comment]
are you ssh-logged onto your NAS?

if you type "pwd" you should get your current directory for instance

**Comment by sticmou** [comment]
Hi

- Install pyload 0.4.9.4 from "packages center" and http://packages.synocommunity.com url.
- I download pyload (pyload-src-v0.4.9.zip) package from "https://github.com/pyload/pyload/releases" and extract it and copy each files by ssh in "/volume1/@appstore/pyload/
- I also modify the UpdateManager.py file to be like Gamma said me.
- Unlock pyload user

And now : 

![pyload](https://cloud.githubusercontent.com/assets/18160117/14198962/25e3de62-f7e0-11e5-8d07-dd9808b1339d.jpg)

**Comment by sticmou** [comment]
Hi

- add these lines on ./pyload/module/network/HTTPRequest.py ( http://mybookworld.wikidot.com/forum/t-540705/pyload-works-new-method )
![1](https://cloud.githubusercontent.com/assets/18160117/14199377/4d0ece62-f7e4-11e5-9c20-1a646e458d38.jpg)

- I create a link for the next error
![1](https://cloud.githubusercontent.com/assets/18160117/14199399/85321f10-f7e4-11e5-9386-48601571b88b.jpg)

- and now, it work on deamon mode :)
![1](https://cloud.githubusercontent.com/assets/18160117/14199441/b8db5cd2-f7e4-11e5-977b-505470b21b22.jpg)

**Comment by GammaC0de** [comment]
@sticmou Try issuing the command `pip install pycurl`, then retry.

**Comment by aronze06** [comment]
Yes, I'm log on my NAS in ssh with putty and after a new try, bellow what I obtained (sorry it in french):
configuration worked and I could execute what you gave me before but I still have the same problem with pyload (no icon) :( 
Sorry to waste your time :(
Alexis
-----------------------
Using username "admin".
admin@xx.xx.xx.xx's password:
admin@DiskStation:~$ sudo -i
Password:
root@DiskStation:~# pwd
/root
root@DiskStation:~# cd /volume1/@appstore/pyload/pyload
root@DiskStation:/volume1/@appstore/pyload/pyload# sudo puthon pyloadcore.py
sudo: puthon: command not found
root@DiskStation:/volume1/@appstore/pyload/pyload# sudo python pyloadcore.py                                                                                                                                   python: can't open file 'pyloadcore.py': [Errno 2] No such file or directory
root@DiskStation:/volume1/@appstore/pyload/pyload# cd /volume1/@appstore/pyload/                                                                                                                               pyload/
root@DiskStation:/volume1/@appstore/pyload/pyload# sudo python pyLoadCore.py                                                                                                                                   This is your first start, running configuration assistent now.
Choose your Language / Wähle deine Sprache ([en], de, fr, it, es, nl, sv, ru, pl                                                                                                                               , cs, sr, pt_BR): fr

Bienvenue dans l'Assistant de Configuration de pyLoad.
Il analysera votre système et effectuera une configuration basique afin de pouvo                                                                                                                               ir exécuter pyLoad.

Les valeurs entre crochets [] sont toujours celles par défauts,
si vous ne souhaitez pas les changer ou si vous n'êtes pas sur de votre choix, a                                                                                                                               ppuyer juste sur entrée.
N'oubliez pas : vous pouvez relancez cet assistant à tout moment en ajoutant les                                                                                                                                paramètres --setup ou -s lorsque vous exécutez pyLoadCore.
Si vous avez un problème avec cet assistant appuyer sur CTRL-C,
pour annuler et l'empêcher de démarrer avec pyLoadCore automatiquement.

Quand vous êtes prêt pour la vérification du système, appuyer sur entrée.

## Vérification du Système ##
Version de Python : OK
pycurl : OK
sqlite3 : OK

pycrypto : absent
py-OpenSSL : absent

py-imaging : absent
tesseract : absent

PyQt4 : absent

jinja2 : OK
beaker : OK
moteur JS : absent

Vérification du système fini, appuyer sur entrée pour voir votre rapport de stat                                                                                                                               us.

## Status ##

Fonctions disponibles : Interface web

Fonctions indisponibles :

py-crypto n'est pas disponible
Vous en avez besoin si vous souhaitez décrypter les fichiers conteneurs.

SSL n'est pas disponible
Vous en avez besoin si vous souhaitez établir une connexion sécurisé avec le log                                                                                                                               iciel principal ou l'interface web.
Si vous souhaitez accéder à pyLoad uniquement en local, ssl n'est pas utile.

La Reconnaissance des catchas n'est pas disponible
Ceci est nécessaire uniquement pour certains hôtes en tant qu'utilisateur gratui                                                                                                                               t.

Interface graphique non disponible
L'Interface Graphique.

pas de moteur JavaScript trouvé
Vous en aurez besoin pour certains liens Click'N'Load. Installez SpiderMonkey, o                                                                                                                               ssp-js, pyv8 ou Rhino
Si vous le souhaitez, vous pouvez maintenant sortir du configurateur et corriger                                                                                                                                certaines dépendances.
Continuer la configuration ? ([o]/n): o

Voulez vous modifier le dossier de configuration ? Pour l'instant il s'agit de /root/.pyload
Si vous utilisez pyLoad sur un serveur ou si la partition home se trouve sur un disque flash il est conseillé de le modifier.
Modifier le dossier de configuration ? (o/[n]): n

Voulez vous configurer les identifiants et les paramètres principaux?
Cette étape est recommandé lors du premier démarrage.
Mettre en place la configuration de base ? ([o]/n): o

## Configuration Basique ##

Les identifiants de connexion suivants sont valide pour la CLI, le GUI et l'interface web.
Nom d'utilisateur [User]: admin
Mot de passe :
Mot de passe (encore) :

External clients (GUI, CLI or other) need remote access to work over the network.
However, if you only want to use the webinterface you may disable it to save ram.
Enable remote access ([o]/n): o

Langage ([en], de, fr, it, es, nl, sv, ru, pl, cs, sr, pt_BR): fr
Dossier de téléchargement [Downloads]: /volume1/Fichiers/pyloadDownload/
Téléchargements parallèle maximum [3]: 3
Utiliser reconnexion ? (o/[n]): o
Emplacement du script de reconnexion [./reconnect.sh]:

Souhaitez vous configurer l'interface web ?
Paramétrer l'interface web ? ([o]/n): o

## Configuration Interface Web ##

Activer l'interface web ? ([o]/n): o

Adresse d'écoute, si vous utilisez 127.0.0.1 ou localhost, l'interface web ne sera accessible que localement.
Adresse [0.0.0.0]:
Port [8000]:

pyLoad propose différents serveurs de gestion, décrits ci-après.
builtin: Serveur par défaut ; c'est le meilleur choix si vous ne savez pas lequel choisir.
threaded: Ce serveur permet l'utilisation de SSL ; c'est une bonne alternative à builtin.
fastcgi: Peut être utilisé par Apache, lighttpd ; vous devez le configurer manuellement, ce qui peut s'avérer difficile.
lightweight: Une alternative très rapide écrite en C, nécessite libev et des connaissances en linux.
        Téléchargez le depuis : https://github.com/jonashaag/bjoern, compilez-le
        et copiez bjoern.so vers module/lib

Attention : dans certain cas le serveur intégré ne marche pas, si vous avez des problèmes avec l'interface web,
revenez ici et changez le serveur de “builtin” à “threaded”.
Serveur ([builtin], threaded, fastcgi, lightweight):

Configuration définie avec succès.
Appuyez sur entrée et redémarrer pyLoad

root@DiskStation:/volume1/@appstore/pyload/pyload#

**Comment by skpyl** [comment]
Hey,
i did what @aronze06 wrote [here](https://github.com/pyload/pyload/issues/2397#issuecomment-203807448) but also changed the owner of my pyload folder (/volume1/@appstore/pyload) to the pyload user and it now works for me.

**Comment by effpi** [comment]
@aronze06 : try to access with a new browser window using your NAS IP address:8000 (normally you log onto your NAS with NAS IP address:5000)
ouvre une autre fenêtre dans ton navigateur et vas à l'adresse "IP du NAS":8000
@skpyl : not working for me, but I will try again from scratch

**Comment by aronze06** [comment]
Do i need to install python for runing pyload ? Or it is include into DSM 6 ?

**Comment by effpi** [comment]
no, it is included into DSM 6

**Comment by aronze06** [comment]
OK so i will uninstall python package and reinstall pyload. I'll keep you informed. Thanks !

**Comment by aronze06** [comment]
Hi  All;
So I have some good news !!!!!
I followed what you said me and pyload seems working fine now but only on "web interface". I still have the same problem when I try to launch pyload on the desktop on my DS211j NAS. The page is empty...
So to add some explanations, during pyload setting, I modify the owner "root" of the pyload folder to "pyload".
Despite, I also have a problem with the onefichier premium account and I have this problem:
"ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128) 0.00 BOneFichierCom"

Thanks a lot to everybody for your help and your time !

Alexis

**Comment by effpi** [comment]
very good, same for me: I only have access with the web interface.
you can as well add the --daemon option when launching pyLoadCore.py which will allow you to close the putty window
for OneFichier, I have a premium account as well and it is working fine... but if you want to share more traces I can have a look (you may need to enable Debug Mode in Configuration / Menu / General)

**Comment by mgg1959** [comment]
Alexis, how do i open the web interface for pyload?, my DSM ip is 192.168.1.7 , thanks

**Comment by effpi** [comment]
Should be 192.168.1.7:8000

**Comment by mgg1959** [comment]
Not for me: http://prntscr.com/aoybp2 Firefox can't establish a connection to the server at 192.168.1.7:8000. , thanks

**Comment by varwone** [comment]
installed pyload via synocommunity. after Update to DSM6 i can start it, but i can't access via webinterface. any ideas?

**Comment by effpi** [comment]
If you did a clean install, you need to run pyload twice from ssh window (not from DSM window), first time will configure, second will correctly use config parameters

You may force configuration by running "sudo python /volume1/@appstore/pyload/pyload/pyLoadCore.py -s"

**Comment by varwone** [comment]
@effpi  you sir deserve a medal! thank you. but now some stuff doesnt work, like dlc decrypter or clicknload. do you know how fix them?

**Comment by GammaC0de** [comment]
@varwone when you had ran pyload's configuration, it checks for dependencies, is there something missing? specially the JS package..

**Comment by varwone** [comment]
@GammaC0de  yes, py-crypto and the java engine are missing. how do I install it? Thx

**Comment by GammaC0de** [comment]
`pip install pycrypto`

for me, `ossp-js` is the package for java

**Comment by aronze06** [comment]
Hi;
I have an issue with pyload to download this file : https://1fichier.com/?dkbl80q0ez
Pyload return me this message: Parse error: No file downloaded | Plugin may be out of date 0.00 B OneFichierCom
Do you have an idea ?
Thanks !

Alexis

**Comment by effpi** [comment]
Alexis: van you check the version of the OneFichier plug-in: go to directory /volume1/@appstore/pyload/pyload/modules/plugins/hoster then look at OneFichierCom.py, (with more command) you should have version 1.0

If not, it means your plugins were not updated, make sure UpdateManager.py is the one referred by Gamma and restart pyLoad
If yes, I have no clue...


Envoyé de mon iPad

**Comment by aronze06** [comment]
Exactly; my OneFichierCom.py plug-in is not up-to-day.
So I'll update it and also change my UpdateManager.py plug-in.

Thanks.

**Comment by varwone** [comment]
@GammaC0de ok thanks. but i think pip is not installed, with which command can i install pip?

**Comment by effpi** [comment]
@varwone: did you try to run pyload from a ssh window (not from DSM)? to do this you need to log onto your NAS with putty on a PC or Terminal on a MAC. Then run "sudo python /volume1/@appstore/pyload/pyload/pyLoadCore.py" and share output to understand error

**Comment by aronze06** [comment]
Everything seems to be ok now except pyload on the NAS desktop. Windows still empty.
Next step, set-up pyload app for iOS ;)

Nice weekend to everybody !

Alexis

**Comment by effpi** [comment]
good to read this, let's wait for someone to fix the DSM package.

try this one, it is free, captcha management weak, but if you use OneFichier premium, probably you don't need this feature
[pyLoad Ctrl 1.2.ipa.zip](https://github.com/pyload/pyload/files/210330/pyLoad.Ctrl.1.2.ipa.zip)

I would recommend to create two servers, one from home network (with local IP address) and one from outside (with either static external IP or DNS forwarder)

enjoy ;-)

and by the way, I may a wrong comment. To check whether you have the latest plug-ins, you need to go to /volume1/@appstore/pyload/var/config/userplugins/hoster

**Comment by GammaC0de** [comment]
Can we close this?

**Comment by varwone** [comment]
@effpi yes sure. 
![image](https://cloud.githubusercontent.com/assets/8791861/14410671/e2d12132-ff34-11e5-8515-cd3a0b2bad29.png)
pip doesn't work.

**Comment by GammaC0de** [comment]
Maybe
sudo apt-get install python-setuptools
This should install pip

**Comment by varwone** [comment]
@GammaC0de apt-get also not installed

**Comment by effpi** [comment]
@varwone what is exactly your error message when you try to launch pyLoad?

**Comment by varwone** [comment]
@effpi there is no error message. pyload is working. i just need to get pycrypto and ossp-js installed for dlc decrypting and clicknload.

**Comment by effpi** [comment]
ok, there I am clueless

**Comment by varwone** [comment]
same issue is written here: https://github.com/pypa/pip/issues/3588
solved installation of pip with "python -m ensurepip" and the updated pip with "pip install --upgrade pip". 
now i'm stuck at "pip install pycrypto", brings up severeal errors. 
![unbenannt](https://cloud.githubusercontent.com/assets/8791861/14432642/47f7e4a2-000b-11e6-9bbf-b2a7d4d96267.PNG)

**Comment by hardyGitHub** [comment]
Got the solution so far!
needed to extract pyLoad-0.4.9-5-avoton.spk. Then I copy all files from pyLoad-0.4.9-5-avoton/package/pyload/module/plugins to /volume1/@appstore/pyload/etc/userplugins. chown pyload.root to all files. Some plugins needed the chmod u+x to make them executable. Finally I had to face this 
Error importing ShareonlineBiz: No module named misc
I downloaded it from 
https://github.com/pyload/pyload/blob/ff880300c3200d0c6adfd2f8f3732a10e06d30ec/module/plugins/internal/misc.py
copied it to /volume1/@appstore/pyload/etc/userplugins/internal, made it executable.
Done works for me.
Seems, that there are some installationroutinemistakes!

**Comment by beuaaa** [comment]
So finally which method works?
1. Enkidu Package of the community package
2. Bootstrap IPKG installation
3. Docker Container

Somebody can summarize the pros and cons of each method?

Can you put some links of tutorials?

**Comment by mgg1959** [comment]
Same as Beuaaa here, as easy as can be!.
Thanks

**Comment by Velociraptor85** [comment]
@mgg1959 @beuaaa maybe you could add a Page to the wiki how you did it? and close this issue than?

**Comment by Velociraptor85** [comment]
@aronze06 @GammaC0de @vuolter 
Since its solved maybe we could close this issue? Main Problem https://github.com/pyload/pyload/issues/2361

**Comment by beuaaa** [comment]
With DSM 5.2 I used this tutorial: http://freshest.me/pyload-in-a-debian-chroot-on-the-ds215j
It was the only method which worked fine for me.

Actually I don't know how to install Pyload on a Synology ds215J since DSM 6. I'm still looking for the simplest solution. So I need some help.

**Comment by mgg1959** [comment]
No updates?

**Comment by lordfiSh** [comment]
just installed pyload on DSM5:
```
wget https://github.com/pyload/pyload/archive/stable.zip
unzip stable.zip
cd pyload-stable
ipkg install py26-curl
wget https://bootstrap.pypa.io/get-pip.py --no-check-certificate
python get-pip.py
pip install beaker thrift simplejson pycrypto
python2.6 pyLoadCore.py
```

**Comment by GammaC0de** [comment]
@lordfiSh Topic is about DSM6 not 5...

**Comment by lordfiSh** [comment]
@GammaC0de should be the same

**Comment by Velociraptor85** [comment]
@lordfiSh @GammaC0de maybe add this to the wiki page?
see https://github.com/pyload/pyload/wiki/Step-by-Step-Installation-(DSM) please change :)

**Comment by GammaC0de** [comment]
@Velociraptor85 Can you confirm this works with DSM6 too?

**Comment by mgg1959** [comment]
How i can do it?, with putty as soon i enter the login info, putty close, thanks

**Comment by GammaC0de** [comment]
@mgg1959 I don't know, I don't own a DSM, maybe someone else here can help..

**Comment by mgg1959** [comment]
ok, i managed to enable the ssh and login with putty, but ipkg is not available on dsm!

**Comment by GammaC0de** [comment]
Maybe this can help
‬https://github.com/Entware-ng/Entware-ng/wiki/Install-on-Synology-NAS

**Comment by mgg1959** [comment]
Thanks a lot, but i will wait if someone can make it in easy way, i hate putty.

**Comment by Velociraptor85** [comment]
@GammaC0de sorry cant, I also dont have an DSM machine
