### ISSUE TITLE
easybytez premium not working 

### ISSUE THREAD

**Issue by kirner** [pyload/pyload#2959]
Hello, seems something goes wrong, cause often goes in waiting time.

642 | 08.09.2017 21:00:09 | INFO | HOSTER EasybytezCom[6130]: Grabbing link info...
-- | -- | -- | --
643 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Link name: *********.rar
644 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Link size: 400.00 MiB (419430400 bytes)
645 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Link status: online
646 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Processing url: http://www.easybytez.com/78otvfzu4an4/*********.rar
647 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Looking for direct download link...
648 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Direct download link not found
649 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Checking for link errors...
650 | 08.09.2017 21:00:10 | WARNING | HOSTER EasybytezCom[6130]: Error happened when generating Download Link.
651 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Waiting 1 minutes...
652 | 08.09.2017 21:00:10 | INFO | HOSTER EasybytezCom[6130]: Requiring reconnection...
653 | 08.09.2017 21:00:10 | WARNING | HOSTER EasybytezCom[6130]: Reconnection ignored due logged account

----------------------------------------------------

as you can see, he goes in waiting time (line 651)

if you need more info, feel free to contact me.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by kirner** [comment]
So, investigating more, seems this is not a plugin problem, i think this is an easybytez issue!
I think after this i can close the thread.
Thx.

**Comment by kirner** [comment]
Hello again, seems this time easybytez plugin have some problems, i checked the files outside of easybytes and all is ok, please give a look to the log, and let me know if i have to forward full link and easybytez account to nitzo2001 
Thx in advance.

971 | 10.10.2017 11:50:09 | INFO | HOSTER EasybytezCom[5158]: Requiring reconnection...
-- | -- | -- | --
970 | 10.10.2017 11:50:09 | INFO | HOSTER EasybytezCom[5158]: Waiting 12 hours, 10 minutes, 50 seconds...
969 | 10.10.2017 11:50:09 | WARNING | HOSTER EasybytezCom[5158]: You have reached the download-limit: 512 Mb for last 1 days
968 | 10.10.2017 11:50:09 | INFO | HOSTER EasybytezCom[5158]: Checking for link errors...
967 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: No errors found
966 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Checking for link errors...
965 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Processing as free download...
964 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: No errors found
963 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Checking for link errors...
962 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Processing url: http://www.easybytez.com/****************************.part002.rev
961 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Link status: online
960 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Link size: 400.00 MiB (419430400 bytes)
959 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Link name: W0ND3R.W0M4N.17.BD.part002.rev
958 | 10.10.2017 11:50:08 | INFO | HOSTER EasybytezCom[5158]: Grabbing link info...
957 | 10.10.2017 11:50:08 | INFO | ACCOUNT EasybytezCom: Grabbing account info for user `kirner`...
956 | 10.10.2017 11:50:08 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
955 | 10.10.2017 11:50:08 | WARNING | HOSTER EasybytezCom[5158]: Plugin may be unstable
954 | 10.10.2017 11:50:08 | INFO | Download starts: http://www.easybytez.com/****************.part002.rev
953 | 10.10.2017 11:50:06 | INFO | ADDON UnSkipOnFail: No duplicates found
952 | 10.10.2017 11:50:06 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: W0ND3R.W0M4N.17.BD.part002.rar (pid:309)
951 | 10.10.2017 11:50:06 | ERROR | pycurl error 6: Could not resolve host: www.easybytez.com
950 | 10.10.2017 11:50:06 | INFO | HOSTER EasybytezCom[5157]: Processing url: http://www.easybytez.com****************************.part002.rar
949 | 10.10.2017 11:50:06 | INFO | HOSTER EasybytezCom[5157]: Link status: avviando
948 | 10.10.2017 11:50:06 | INFO | HOSTER EasybytezCom[5157]: Link size: N/D
947 | 10.10.2017 11:50:06 | INFO | HOSTER EasybytezCom[5157]: Link name: W0ND3R.W0M4N.17.BD.part002.rar
946 | 10.10.2017 11:50:06 | INFO | HOSTER EasybytezCom[5157]: Grabbing link info...
945 | 10.10.2017 11:50:06 | WARNING | ACCOUNT EasybytezCom: Error loading info for user `kirner` \| (6, 'Could not resolve host: www.easybytez.com')
944 | 10.10.2017 11:50:06 | INFO | ACCOUNT EasybytezCom: Grabbing account info for user `kirner`...
943 | 10.10.2017 11:50:06 | WARNING | HOSTER EasybytezCom[5157]: Plugin may be unstable
942 | 10.10.2017 11:50:06 | INFO | Download starts: http://www.easybytez.com/***********.part002.rar
941 | 10.10.2017 11:50:04 | INFO | ADDON UnSkipOnFail: No duplicates found
940 | 10.10.2017 11:50:04 | INFO | ADDON UnSkipOnFail: Looking for skipped duplicates of: W0ND3R.W0M4N.17.BD.part001.rev (pid:309)
939 | 10.10.2017 11:50:04 | ERROR | pycurl error 6: Could not resolve host: www.easybytez.com
938 | 10.10.2017 11:50:04 | INFO | HOSTER EasybytezCom[5156]: Processing url: http://www.easybytez.com**************.rev

**Comment by GammaC0de** [comment]
```
ACCOUNT EasybytezCom: Error loading info for user kirner | (6, 'Could not resolve host: www.easybytez.com')
```
You have internet connection issue.

**Comment by kirner** [comment]
absolutely not, i was playng with dnsmasq in the while so i got this... but as you can see from a new log no curl dns error.. just easybytez account, sorry for spamming log again :(


1100 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5160]: Link size: 400.00 MiB (419430400 bytes)
-- | -- | -- | --
1101 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5161]: Link name: W0ND3R.W0M4N.17.BD.part004.rar
1102 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5159]: Checking for link errors...
1103 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5160]: Link status: online
1104 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5161]: Link size: 400.00 MiB (419430400 bytes)
1105 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5160]: Processing url: http://www.easybytez.com/*****.part003.rev
1106 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5161]: Link status: online
1107 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5159]: No errors found
1108 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5159]: Processing as free download...
1109 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5159]: Checking for link errors...
1110 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5161]: Processing url: http://www.easybytez.com/******.part004.rar
1111 | 10.10.2017 12:51:04 | INFO | HOSTER EasybytezCom[5159]: No errors found
1112 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Checking for link errors...
1113 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: No errors found
1114 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Processing as free download...
1115 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Checking for link errors...
1116 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: No errors found
1117 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Checking for link errors...
1118 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: No errors found
1119 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Processing as free download...
1120 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Checking for link errors...
1121 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: No errors found
1122 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5159]: Checking for link errors...
1123 | 10.10.2017 12:51:05 | WARNING | HOSTER EasybytezCom[5159]: You have reached the download-limit: 512 Mb for last 1 days
1124 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5159]: Waiting 11 hours, 9 minutes, 54 seconds...
1125 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5159]: Requiring reconnection...
1126 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Checking for link errors...
1127 | 10.10.2017 12:51:05 | WARNING | HOSTER EasybytezCom[5161]: You have reached the download-limit: 512 Mb for last 1 days
1128 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Waiting 11 hours, 9 minutes, 54 seconds...
1129 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5161]: Requiring reconnection...
1130 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Checking for link errors...
1131 | 10.10.2017 12:51:05 | WARNING | HOSTER EasybytezCom[5160]: You have reached the download-limit: 512 Mb for last 1 days
1132 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Waiting 11 hours, 9 minutes, 54 seconds...
1133 | 10.10.2017 12:51:05 | INFO | HOSTER EasybytezCom[5160]: Requiring reconnection...

**Comment by GammaC0de** [comment]
OK, so please send account and URL.

**Comment by kirner** [comment]
done ;)

**Comment by GammaC0de** [comment]
Can you look in pyload's accounts page an tell if it says that EasybytezCom is premium or not?

**Comment by kirner** [comment]
Status is Valid, and premium is no.

**Comment by GammaC0de** [comment]
OK, 
So this is the cause of this issue.
What happens after you restart pyload, still not premium ?

I have to ask, did you changed to the test password?

**Comment by kirner** [comment]
so.. previously i have changed the pw and premium was no, but i have not restartarted it, now  after a restart the status is valid and premium is yes with the expiry date.

**Comment by GammaC0de** [comment]
Ok, so I guess now downloads works fine, right?

If so, we have to verify that it stays premium even after some time.

First, please enable DEBUG mode in pyload .
Now download normally and if this issue happens again, please post the relevant log with the debug info.

**Comment by kirner** [comment]
So, i'm sorry to tell you this but download status is always the same, i started pyload in debug mode and here is the log:


242 | 10.10.2017 16:28:51 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
-- | -- | -- | --
243 | 10.10.2017 16:28:51 | INFO | Download restarted: **********.part006.rev \| Fallback to free processing
244 | 10.10.2017 16:28:51 | INFO | Download starts: *********.part006.rev
245 | 10.10.2017 16:28:51 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
246 | 10.10.2017 16:28:51 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
247 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: Plugin version: 0.28
248 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: Plugin status: testing
249 | 10.10.2017 16:28:51 | WARNING | HOSTER EasybytezCom[5166]: Plugin may be unstable
250 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: Config option `use_premium` not found, use default `True`
251 | 10.10.2017 16:28:51 | INFO | HOSTER EasybytezCom[5166]: Grabbing link info...
252 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: Link info: {'status': 2, 'hash': {}, 'name': u'W0ND3R.W0M4N.17.BD.part006.rev', 'url': u'http://www.easybytez.com/***********.rev', 'pattern': {'S': u'400.0', 'U': u'MB', 'N': u'***********.part006.rev'}, 'size': 419430400}
253 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: Previous link info: {'status': 2, 'hash': {}, 'name': u'********.part006.rev', 'url': u'http://www.easybytez.com/sioid23hzh02/*******.part006.rev', 'pattern': {'S': u'400.0', 'U': u'MB', 'N': u'*******.part006.rev'}, 'size': 419430400}
254 | 10.10.2017 16:28:51 | INFO | HOSTER EasybytezCom[5166]: Link name: W0ND3R.W0M4N.17.BD.part006.rev
255 | 10.10.2017 16:28:51 | INFO | HOSTER EasybytezCom[5166]: Link size: 400.00 MiB (419430400 bytes)
256 | 10.10.2017 16:28:51 | INFO | HOSTER EasybytezCom[5166]: Link status: online
257 | 10.10.2017 16:28:51 | INFO | HOSTER EasybytezCom[5166]: Processing url: http://www.easybytez.com/sioid23hzh02/*******.part006.rev
258 | 10.10.2017 16:28:51 | DEBUG | HOSTER EasybytezCom[5166]: LOAD URL http://www.easybytez.com/sioid23hzh02/********.part006.rev \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
259 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Checking for link errors...
260 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: No errors found
261 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Processing as free download...
262 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: Getting download link #1...
263 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Checking for link errors...
264 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: No errors found
265 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: {u'method_premium': u'Premium Download', u'usr_login': '', u'referer': '', u'fname': u'*********.part006.rev', u'method_free': u'Free Download', u'id': u'sioid23hzh02', u'op': u'download1'}
266 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: LOAD URL http://www.easybytez.com/sioid23hzh02/******.part006.rev \| redirect=False \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={u'usr_login': '', u'referer': '', u'fname': u'*****.part006.rev', u'method_free': 'Free Download', u'id': u'sioid23hzh02', u'op': u'download1'} \| ref=True \| just_header=False
267 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: Getting download link #2...
268 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Checking for link errors...
269 | 10.10.2017 16:28:52 | WARNING | HOSTER EasybytezCom[5166]: You have reached the download-limit: 512 Mb for last 1 days
270 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: Config option `max_wait` not found, use default `10`
271 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: WAIT set to timestamp 1507672860.508576 \| Previous waitUntil: 0.000000
272 | 10.10.2017 16:28:52 | DEBUG | HOSTER EasybytezCom[5166]: RECONNECT required \| Previous wantReconnect: False
273 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Waiting 7 hours, 32 minutes, 7 seconds...
274 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Requiring reconnection...

**Comment by GammaC0de** [comment]
`261 | 10.10.2017 16:28:52 | INFO | HOSTER EasybytezCom[5166]: Processing as free download...`

It starts a free download, not premium.

I tried the URL and the account you have sent me it it worked fine, I suggest you refresh your pyload installation ( at least the plugins)..

**Comment by kirner** [comment]
Finally I found some spare time to check more...
So after a fresh install issue was always the same, so I checked more, and I have discovered which was the real problem. So if pyload doesn't find the download folder this is what happen, don't ask me why... if I can I suggest to add in when payload start a check to the download folder. Thx.
