### ISSUE TITLE
Legacy decorator not working in the API

### ISSUE THREAD

**Issue by RemiRigal** [pyload/pyload#4095]
### Description

My application requires calls to the API and I would like to support both PyLoad and PyLoad-Ng. The legacy endpoints written in camel case (`checkURLs` for example) work well with PyLoad but do not work with PyLoad-Ng. I know that they now are in snake case (`checkURLs` became `check_urls` for example) but they should still work since the API script uses the `legacy` decorator like this:

https://github.com/pyload/pyload/blob/4b0c6b64fd7590a09bcf95866f7a29259a64ee04/src/pyload/core/api/__init__.py#L74-L84

https://github.com/pyload/pyload/blob/4b0c6b64fd7590a09bcf95866f7a29259a64ee04/src/pyload/core/api/__init__.py#L466-L484

Am I missing something ? Thank you.

### Debug log

None

### Additional references

None

### Screenshots

None

**Comment by GammaC0de** [comment]
This has already been fixed in the develop branch.

P.S.
Why yape is not on the Firefox add-ons site anymore?

**Comment by RemiRigal** [comment]
Great, thank you for the quick reply ! Do you have an estimation for when the new changes will be merged ?

I need to publish a new version for the Firefox add-on, I'm working on it.

**Comment by GammaC0de** [comment]
In a few days.
Meanwhile you can install the development version using: `pip install --upgrade https://github.com/pyload/pyload/archive/refs/heads/develop.zip`

**Comment by RemiRigal** [comment]
Awesome, thank you !

**Comment by milahu** [comment]
still a problem

statusDownloads returns boolean (true/false) instead of array

statusServer works = returns object

```py
    @legacy("statusServer")
    @permission(Perms.LIST)
    def status_server(self):
```

statusDownloads fails = returns bool

```py
    @legacy("statusDownloads")
    @permission(Perms.LIST)
    def status_downloads(self):
```

the function `status_downloads` returns an array, but then it's converted to true

the array arrives on the client side with

```py
    @legacy("statusDownloads")
    @permission(Perms.LIST)
    def status_downloads(self):
        return [ "test" ] # ok
```

why true?

`webui/app/blueprints/api_blueprint.py`

```py
    # null is invalid json response
    return jsonify(result or True)
```

`[]` is falsy, so it picks True
